### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by buzz** [buzz/newsdash#29]
Add a dark theme, available from options.

**Comment by tumidi** [comment]
See CSS [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

**Comment by buzz** [comment]
See CSS [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

**Comment by buzz** [comment]
Done in v1.0.0
