### ISSUE TITLE
Grid layout not consistent after refresh

### ISSUE THREAD

**Issue by jeannotalpin** [buzz/newsdash#63]
Hi,
Great project you have here. I have deployed it on my raspberry and is a great substitute to netvibes :)

I have an issue with the grid layout that is not kept after refresh. I have around 15 cells in the grid, set to 6 columns. 
Some have a size of 2 (3 cells per line), some of 3 (2 cells per line) and some of 6 (1 cell per line). After a refresh, all the cells (size and place) are changed as if the table size was reduced, See attached screenshot for more details.

Thanks.
![initial_state](https://user-images.githubusercontent.com/480536/146737799-2214bd8c-b447-467e-bc81-de870df42468.png)

![after_refresh](https://user-images.githubusercontent.com/480536/146737790-3f74d4f9-5c34-4562-8778-62d2743d482e.png)

**Comment by buzz** [comment]
Could you try the fix in 504c2b1? It should fix the issue.

**Comment by jeannotalpin** [comment]
I tried your fix and although a change is noticeable, it appears that my grid of 6 always comes back to a grid of 4.

**Comment by buzz** [comment]
Ok, I understand you are using the API-less mode. It's less tested and not really recommended as it comes with downsides. There's was a bug that I've fixed, so it should work in latest version.
